Repository AY1920S1-CS2103T-F11-4/main, pull requests merged in 2019-10, with the labels that each got.

#11 Update AboutUs
  docs/AboutUs.adoc
  docs/images/auxinnn.png
  docs/images/irene-lly.png
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/shirleywangxt.png
  docs/images/shuiyao-sg.png
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
Labels: priority.High, severity.High, type.Task

#12 Modify Ui.png
  docs/images/Ui.png
Labels: priority.High, severity.High, type.Task

#13 Command transplanting, part 1
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
Labels: priority.High, severity.High, type.Task

#14 [Wang Xueting] Modify User guide
  docs/UserGuide.adoc
Labels: priority.High, severity.High, type.Task

#15 Modify userguide for statistics feature
  docs/UserGuide.adoc
Labels: priority.High, severity.High, type.Task

#16 [SHUI YAO] Add revision task features to UserGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, severity.High, type.Task

#17 Update user stories
  docs/DeveloperGuide.adoc
Labels: priority.High, severity.High, type.Task

#19 [SHUI YAO] Add User Stories
  docs/DeveloperGuide.adoc
Labels: priority.High, severity.High, type.Task

#18 [Wang Xueting] Modify user stories on difficulty feature in developer guide
  docs/DeveloperGuide.adoc
Labels: priority.High, severity.High, type.Task

#21 Fill in remaining fields of the developer guide
  docs/DeveloperGuide.adoc
Labels: priority.High, severity.High, type.Task

#20 Modify user stories
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, severity.High, type.Task

#22 Patch in product scope and value proposition
  docs/DeveloperGuide.adoc
Labels: priority.High, severity.High, type.Task

#23 [SHUI YAO]Add use cases for revision feature
  docs/DeveloperGuide.adoc
Labels: priority.High, severity.High, type.Task

#24 Modify use cases
  docs/DeveloperGuide.adoc
Labels: priority.High, severity.High, type.Task

#25 [Wang Xueting] Modify use cases for difficulty in developer guide.
  docs/DeveloperGuide.adoc
Labels: priority.High, severity.High, type.Task

#27 Polish up user and developer guide after hackathon
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, severity.High, type.Task

#28 [Zhang Dongjun] Update test mode feature in UG, user stories and use cases in DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, severity.High, type.Task

#30 Last user and developer guide polishing for 1.1
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, severity.High, type.Task

#29 [SHUI YAO]Delete Command Summary in UserGuide.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, severity.High, type.Task

#33 Add additional furtive feature
  docs/UserGuide.adoc
Labels: priority.Low, severity.Low, type.Enhancement

#35 Remove tutorials (?)
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/remove/$address.png
  docs/images/remove/SafeDeleteConflicts.png
  docs/images/remove/UnsafeDelete.png
  docs/images/remove/UnsafeDeleteOnField.png
  docs/images/tracing/DebuggerStep1.png
  docs/images/tracing/EditCommand.png
  docs/images/tracing/Execute.png
  docs/images/tracing/FindUsages.png
  docs/images/tracing/LeftGutter.png
  docs/images/tracing/LogicSequenceDiagram.png
  docs/images/tracing/ShowExecutionPoint.png
  docs/images/tracing/StepInto.png
  docs/images/tracing/StepOver.png
  docs/images/tracing/StructureToolWindow.png
  docs/images/tracing/Variables.png
  docs/tutorials/RemovingFields.adoc
  docs/tutorials/TracingCode.adoc
Labels: priority.Medium, severity.Low, type.Task

#37 [SHUI YAO] Add Task class to represent revision tasks
  src/main/java/seedu/address/model/note/UniqueNoteList.java
  src/main/java/seedu/address/model/task/NoteStub.java
  src/main/java/seedu/address/model/task/QuestionStub.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskForNote.java
  src/test/java/seedu/address/model/task/TaskTest.java
Labels: priority.High, severity.High, type.Enhancement, type.Story

#40 More implementations on the quiz mode command
  src/main/java/seedu/address/logic/commands/quiz/QuizModeCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/quiz/QuizQuestionList.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
Labels: priority.High, severity.High, type.Enhancement

#41 Updates on quiz feature
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/quiz/QuitQuizModeCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizCheckAnswer.java
  src/main/java/seedu/address/logic/commands/quiz/QuizModeCommand.java
  src/main/java/seedu/address/logic/parser/quiz/QuitQuizModeParser.java
  src/main/java/seedu/address/logic/parser/quiz/QuizAnswerParser.java
  src/main/java/seedu/address/logic/parser/quiz/QuizParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/quiz/QuizQuestionList.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
Labels: priority.High, severity.High, type.Enhancement, type.Story

#42 Reintroduce project portfolio pages, but customised
  docs/UserGuide.adoc
  docs/team/PortfolioParclyTaxel.adoc
Labels: priority.Medium, severity.Low, type.Enhancement, type.Story, type.Task

#43 [SHUI YAO] Implement command for adding a task
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTaskForNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/task/AddTaskForNoteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/note/UniqueNoteList.java
  src/main/java/seedu/address/model/task/NoteStub.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskForNote.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedTaskForNote.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskListCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, severity.High, type.Enhancement

#44 [Wang Xueting] Add addq logic and modify relevant models
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/questioncommands/AddQuestionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/questionparser/AddQuestionCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/question/Answer.java
  src/main/java/seedu/address/model/question/Content.java
  src/main/java/seedu/address/model/question/Question.java
  src/main/java/seedu/address/model/question/QuestionBody.java
  src/main/java/seedu/address/model/question/UniqueQuestionList.java
  src/main/java/seedu/address/model/question/exceptions/DuplicateQuestionException.java
  src/main/java/seedu/address/model/question/exceptions/QuestionNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High, severity.High, type.Enhancement

#46 Remove Coveralls and further develop the project portfolio
  .travis.yml
  build.gradle
  docs/AboutUs.adoc
  docs/DevOps.adoc
  docs/DeveloperGuide.adoc
  docs/SettingUp.adoc
  docs/UserGuide.adoc
  docs/UsingCoveralls.adoc
  docs/UsingGradle.adoc
  docs/UsingTravis.adoc
  docs/images/coveralls/badge_repo.png
  docs/images/coveralls/coverage_asciidoc_code.png
  docs/images/coveralls/coverage_report.png
  docs/images/coveralls/disable_comments.png
  docs/images/coveralls/flick_repository_switch.png
  docs/images/coveralls/github_settings.png
  docs/images/coveralls/sync_repos.png
  docs/team/PortfolioParclyTaxel.adoc
  gradle.properties
Labels: priority.Medium, severity.Medium, type.Story, type.Task

#45 [Irene] Implement a skeleton of statistics feature
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetQnsCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetReportCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetStatisticsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetQnsCommandParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetReportCommandParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetStatisticsCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/statistics/Statistics.java
  src/main/java/seedu/address/model/statistics/StatisticsStub.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatsChart.java
  src/main/resources/view/StatsChart.fxml
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High, severity.High, type.Enhancement, type.Story

#47 [Zhang Dongjun] Updates quiz implementation
  src/main/java/seedu/address/logic/commands/quiz/QuizShowAnswerCommand.java
  src/main/java/seedu/address/logic/parser/quiz/QuizParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/quiz/QuizQuestionList.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#48 [SHUI YAO] Implement done command for tasks
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/task/AddTaskForNoteCommand.java
  src/main/java/seedu/address/logic/commands/task/ClearTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/DoneTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/task/AddTaskForNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/task/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/DoneTaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/task/exceptions/RedundantOperationException.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
Labels: priority.High, severity.Medium, type.Enhancement

#50 Don't truncate lecture note title and content
  src/main/resources/view/NoteListCard.fxml
Labels: priority.Low, severity.Low, type.Bug, type.Enhancement, type.Story

#51 [SHUI YAO] Fix: GUI not showing done task status icon change
  docs/AboutUs.adoc
  docs/team/PortfolioShuiYao.adoc
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
Labels: priority.Medium, severity.Low

#54 Show Kuzka's mother to the original developers
  docs/UserGuide.adoc
  docs/team/PortfolioParclyTaxel.adoc
  src/main/java/seedu/address/logic/commands/ClearNoteCommand.java
  src/main/java/seedu/address/logic/commands/ListNoteCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
Labels: priority.Low, severity.Low, type.Story, type.Task

#53 Branch quiz result
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/quiz/QuizCheckAnswer.java
  src/main/java/seedu/address/logic/commands/quiz/QuizModeCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizShowAnswerCommand.java
  src/main/java/seedu/address/logic/parser/quiz/QuizAnswerParser.java
  src/main/java/seedu/address/logic/parser/quiz/QuizModeCommandParser.java
  src/main/java/seedu/address/logic/parser/quiz/QuizParser.java
  src/main/java/seedu/address/logic/parser/quiz/QuizShowAnswerParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/quiz/QuizQuestionList.java
  src/main/java/seedu/address/model/quiz/QuizResult.java
  src/main/java/seedu/address/model/quiz/QuizResultList.java
  src/main/java/seedu/address/storage/JsonAdaptedQuizResult.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/QuizResultBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, severity.Medium, type.Enhancement

#55 [Wang Xueting] Implement listq and deleteq features for Question
  src/main/java/seedu/address/logic/commands/questioncommands/DeleteQuestionCommand.java
  src/main/java/seedu/address/logic/commands/questioncommands/ListQuestionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/questionparser/DeleteQuestionCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/QuestionListCard.java
  src/main/java/seedu/address/ui/QuestionListPanel.java
Labels: priority.High, severity.High, type.Enhancement

#58 Remove address book branding from logs and docs
  build.gradle
  docs/DevOps.adoc
  docs/DeveloperGuide.adoc
  docs/Documentation.adoc
  docs/SettingUp.adoc
  docs/Testing.adoc
  docs/UsingCheckstyle.adoc
  docs/UsingGradle.adoc
  docs/UsingNetlify.adoc
  docs/UsingTravis.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement, type.Story, type.Task

#59 Refactor developer guide
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/team/PortfolioParclyTaxel.adoc
Labels: priority.High, severity.High, type.Enhancement, type.Story, type.Task

#63 Package note-related commands
  src/main/java/seedu/address/logic/commands/note/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/note/ClearNoteCommand.java
  src/main/java/seedu/address/logic/commands/note/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/note/EditNoteCommand.java
  src/main/java/seedu/address/logic/commands/note/FindNoteCommand.java
  src/main/java/seedu/address/logic/commands/note/ListNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/AppDataParser.java
  src/main/java/seedu/address/logic/parser/DeleteNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindNoteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditNoteDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AppDataParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindNoteCommandParserTest.java
  src/test/java/seedu/address/testutil/EditNoteDescriptorBuilder.java
  src/test/java/seedu/address/testutil/NoteUtil.java
Labels: priority.Medium, severity.Medium, type.Enhancement, type.Task

#62 DG for quiz feature
  docs/DeveloperGuide.adoc
  docs/diagrams/QuizModeActivityDiagram.puml
  docs/diagrams/QuizModeSequenceDiagram.puml
  docs/images/QuizModeActivityDiagram.png
  docs/images/QuizModeSequenceDiagram.png
Labels: priority.Medium, severity.Medium, type.Enhancement

#64 [SHUI YAO] Update DG: Add task feature
  docs/DeveloperGuide.adoc
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/ClassDiagramStyle.puml
  docs/diagrams/TaskClassDiagram.puml
  docs/images/AddTaskSequenceDiagram.png
  docs/images/TaskClassDiagram.png
Labels: priority.High, severity.High, type.Enhancement

#65 [Irene] Update developer guide with Statistics implementation
  docs/DeveloperGuide.adoc
  docs/diagrams/StatisticsActivityDiagram.puml
  docs/diagrams/StatisticsClassDiagram.puml
  docs/diagrams/StatisticsSequenceDiagram.puml
  docs/images/StatisticsActivityDiagram.png
  docs/images/StatisticsClassDiagram.png
  docs/images/StatisticsSequenceDiagram.png
Labels: priority.High, severity.High, type.Enhancement

#67 Implement images in lecture notes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ImageSelectionSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ImageSelectionSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoSequenceDiagram.png
  docs/team/PortfolioParclyTaxel.adoc
  src/main/java/seedu/address/logic/commands/note/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/note/EditNoteCommand.java
  src/main/java/seedu/address/logic/parser/AppDataParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/note/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/note/DeleteNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/note/EditNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/note/FindNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/note/NoteImageSelector.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/ui/NoteCard.java
  src/main/resources/view/NoteListCard.fxml
  src/test/java/seedu/address/logic/parser/AddNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindNoteCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedNoteTest.java
Labels: priority.High, severity.High, type.Enhancement

#68 Add image support to the portfolio
  docs/team/PortfolioParclyTaxel.adoc
Labels: priority.Medium, severity.Medium, type.Enhancement, type.Task

#70 Allow Question and Quiz using same panel
  src/main/java/seedu/address/logic/commands/quiz/QuizCheckAnswer.java
  src/main/java/seedu/address/logic/commands/quiz/QuizShowAnswerCommand.java
  src/main/java/seedu/address/logic/parser/quiz/QuizAnswerParser.java
  src/main/java/seedu/address/model/quiz/QuizQuestionList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, severity.Medium, type.Enhancement

#71 Replace icon for NUStudy
  docs/team/PortfolioParclyTaxel.adoc
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizCheckAnswer.java
  src/main/java/seedu/address/logic/commands/quiz/QuizModeCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizShowAnswerCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetQnsCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetStatisticsCommand.java
  src/main/java/seedu/address/model/AppData.java
  src/main/java/seedu/address/storage/JsonSerializableAppData.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/nustudy.png
  src/main/resources/images/nustudy.svg
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, severity.High, type.Enhancement, type.Story

#72 Purge redundant icons
  docs/team/PortfolioParclyTaxel.adoc
  src/main/resources/images/calendar.png
  src/main/resources/images/clock.png
  src/main/resources/images/fail.png
  src/main/resources/images/help_icon.png
  src/main/resources/images/info_icon.png
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Low, severity.Low, type.Bug

#73 Properly implement lecture note clearing
  src/main/java/seedu/address/logic/commands/note/ClearNoteCommand.java
  src/main/java/seedu/address/model/AppData.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearNoteCommandTest.java
Labels: priority.Low, severity.Low, type.Enhancement

#74 Update for quiz result
  src/main/java/seedu/address/logic/commands/quiz/QuizCheckAnswer.java
  src/main/java/seedu/address/model/quiz/QuizResult.java
  src/main/java/seedu/address/storage/JsonAdaptedQuizResult.java
  src/test/data/JsonSerializableAppDataTest/duplicateAppData.json
  src/test/data/JsonSerializableAppDataTest/invalidAppData.json
  src/test/data/JsonSerializableAppDataTest/typicalAppData.json
  src/test/java/seedu/address/testutil/QuizResultBuilder.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#75 [SHUI YAO] Modify Class Diagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PanelPackageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PanelPackageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/panels/NoteCard.java
  src/main/java/seedu/address/ui/panels/NoteListPanel.java
  src/main/java/seedu/address/ui/panels/PanelComponent.java
  src/main/java/seedu/address/ui/panels/QuestionListCard.java
  src/main/java/seedu/address/ui/panels/QuestionListPanel.java
  src/main/java/seedu/address/ui/panels/QuizQuestionListCard.java
  src/main/java/seedu/address/ui/panels/QuizQuestionListPanel.java
  src/main/java/seedu/address/ui/panels/TaskListCard.java
  src/main/java/seedu/address/ui/panels/TaskListPanel.java
  src/test/data/JsonSerializableAppDataTest/duplicateAppData.json
  src/test/data/JsonSerializableAppDataTest/duplicateTaskData.json
  src/test/data/JsonSerializableAppDataTest/invalidAppData.json
  src/test/data/JsonSerializableAppDataTest/typicalAppData.json
  src/test/java/seedu/address/storage/JsonSerializableAppDataTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppData.java
Labels: priority.High, severity.High, type.Documentation, type.Enhancement

#78 Correctly indicate names for command results
  docs/diagrams/AddQuestionSequenceDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/QuizModeSequenceDiagram.puml
  docs/diagrams/StatisticsSequenceDiagram.puml
  docs/images/AddQuestionSequenceDiagram.png
  docs/images/AddTaskSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/QuizModeSequenceDiagram.png
  docs/images/StatisticsSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/note/NoteImageSelector.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#76 Modification of quiz mode
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/quiz/QuizCheckAnswer.java
  src/main/java/seedu/address/logic/commands/quiz/QuizShowAnswerCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizSkipQuestion.java
  src/main/java/seedu/address/logic/parser/quiz/QuizAnswerParser.java
  src/main/java/seedu/address/logic/parser/quiz/QuizParser.java
  src/main/java/seedu/address/logic/parser/quiz/QuizShowAnswerParser.java
  src/main/java/seedu/address/model/AppData.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/quiz/QuizQuestionList.java
  src/main/java/seedu/address/model/quiz/exceptions/EmptyQuizQuestionException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/panels/QuizQuestionListCard.java
  src/main/java/seedu/address/ui/panels/QuizQuestionListPanel.java
  src/main/resources/view/QuizQuestionListCard.fxml
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
Labels: priority.High, severity.High, type.Enhancement

#79 [Irene] Modify some statistics commands
  docs/UserGuide.adoc
  docs/images/StatisticsActivityDiagram.png
  docs/images/StatisticsClassDiagram.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/statistics/GetOverviewqCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetQnsCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetStatisticsCommand.java
  src/main/java/seedu/address/logic/commands/statistics/Type.java
  src/main/java/seedu/address/logic/parser/AppDataParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetOverviewqCommandParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetQnsCommandParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetStatisticsCommandParser.java
  src/main/java/seedu/address/model/AppData.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/quiz/FilterType.java
  src/main/java/seedu/address/model/quiz/QuizResult.java
  src/main/java/seedu/address/model/quiz/QuizResultFilter.java
  src/main/java/seedu/address/model/quiz/QuizResultList.java
  src/main/java/seedu/address/model/quiz/exceptions/EmptyQuizResultListException.java
  src/main/java/seedu/address/model/quiz/exceptions/FilterTypeNotFoundException.java
  src/main/java/seedu/address/model/quiz/exceptions/WrongDateFormatException.java
  src/main/java/seedu/address/model/statistics/StackBarChartModel.java
  src/main/java/seedu/address/model/statistics/Statistics.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/statistics/StackBarChart.java
  src/main/java/seedu/address/ui/statistics/StatsPieChart.java
  src/main/java/seedu/address/ui/statistics/StatsQnsList.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StackBarChart.fxml
  src/main/resources/view/StatsPieChart.fxml
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#81 Implement defensive copy of images
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ImageSelectionSequenceDiagram.puml
  docs/images/ImageSelectionSequenceDiagram.png
  docs/images/screenshots/addnote.png
  docs/images/screenshots/index.png
  docs/team/PortfolioParclyTaxel.adoc
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/logic/commands/note/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/note/EditNoteCommand.java
  src/main/java/seedu/address/logic/parser/note/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/note/EditNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/note/NoteImageSelector.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/statistics/StackBarChart.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.High, type.Documentation, type.Enhancement, type.Story

#82 [SHUI YAO] Add testing for Task and TaskList
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/commands/task/AddTaskForNoteCommand.java
  src/main/java/seedu/address/logic/commands/task/AddTaskForQuestionCommand.java
  src/main/java/seedu/address/logic/commands/task/DoneTaskCommand.java
  src/main/java/seedu/address/model/task/Heading.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskForNote.java
  src/main/java/seedu/address/model/task/TaskForQuestion.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/test/data/JsonSerializableAppDataTest/duplicateAppData.json
  src/test/java/seedu/address/model/task/HeadingTest.java
  src/test/java/seedu/address/model/task/TaskListTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
Labels: priority.High, severity.High, type.Bug

#84 [Wang Xueting] Implement test cases for question model and commands
  src/main/java/seedu/address/logic/commands/questioncommands/DeleteQuestionCommand.java
  src/test/data/JsonSerializableAppDataTest/typicalAppData.json
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/questioncommands/AddQuestionCommandTest.java
  src/test/java/seedu/address/logic/commands/questioncommands/DeleteQuestionCommandTest.java
  src/test/java/seedu/address/logic/commands/questioncommands/EditQuestionCommandTest.java
  src/test/java/seedu/address/logic/commands/questioncommands/EditQuestionDescriptorTest.java
  src/test/java/seedu/address/logic/commands/questioncommands/FindQuestionCommandTest.java
  src/test/java/seedu/address/logic/commands/questioncommands/ListQuestionCommandTest.java
  src/test/java/seedu/address/logic/parser/AppDataParserTest.java
  src/test/java/seedu/address/model/AppDataTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/question/AnswerTest.java
  src/test/java/seedu/address/model/question/BodyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/question/DifficultyTest.java
  src/test/java/seedu/address/model/question/QuestionBodyTest.java
  src/test/java/seedu/address/model/question/QuestionTest.java
  src/test/java/seedu/address/model/question/SubjectTest.java
  src/test/java/seedu/address/model/question/UniqueQuestionListTest.java
  src/test/java/seedu/address/storage/JsonSerializableAppDataTest.java
  src/test/java/seedu/address/testutil/AppDataBuilder.java
  src/test/java/seedu/address/testutil/EditQuestionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/QuestionBuilder.java
  src/test/java/seedu/address/testutil/QuestionUtil.java
  src/test/java/seedu/address/testutil/TypicalAppData.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#85 [Irene] Implement further commands for statistics feature
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/irene-lly.adoc
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/statistics/GetOverviewCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetQnsCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetReportCommand.java
  src/main/java/seedu/address/logic/commands/statistics/Type.java
  src/main/java/seedu/address/logic/parser/AppDataParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetOverviewCommandParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetReportCommandParser.java
  src/main/java/seedu/address/model/AppData.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/quiz/QuizResult.java
  src/main/java/seedu/address/model/quiz/QuizResultFilter.java
  src/main/java/seedu/address/model/quiz/QuizResultList.java
  src/main/java/seedu/address/model/statistics/TempStatsQnsModel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/statistics/StatsPieChart.java
  src/main/java/seedu/address/ui/statistics/StatsQns.java
  src/main/java/seedu/address/ui/statistics/StatsQnsList.java
  src/main/java/seedu/address/ui/statistics/StatsQnsListCard.java
  src/main/resources/view/StatsQns.fxml
  src/main/resources/view/StatsQnsList.fxml
  src/main/resources/view/StatsQnsListCard.fxml
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/testutil/TypicalAppData.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#86 Fix a few more unsafe generics usages
  build.gradle
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/statistics/StatsQns.java
Labels: priority.Low, severity.Low, type.Bug

#87 [Zhang Dongjun] Implement test cases for quiz result
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/quiz/QuizSkipQuestion.java
  src/main/java/seedu/address/logic/parser/quiz/QuitQuizModeParser.java
  src/main/java/seedu/address/logic/parser/quiz/QuizParser.java
  src/main/java/seedu/address/logic/parser/quiz/QuizShowAnswerParser.java
  src/test/data/JsonSerializableAppDataTest/typicalAppData.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AppDataTest.java
  src/test/java/seedu/address/model/quiz/QuizResultTest.java
  src/test/java/seedu/address/testutil/TypicalAppData.java
Labels: priority.Low, severity.Medium, type.Enhancement

#89 [Irene] Some modifications for statistics feature
  src/main/java/seedu/address/logic/commands/statistics/GetOverviewCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetQnsCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetReportCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetStatisticsCommand.java
  src/main/java/seedu/address/logic/parser/statistics/GetOverviewCommandParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetQnsCommandParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetReportCommandParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetStatisticsCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/quiz/FilterType.java
  src/main/java/seedu/address/model/quiz/QuizResult.java
  src/main/java/seedu/address/model/quiz/QuizResultFilter.java
  src/main/java/seedu/address/model/quiz/QuizResultList.java
  src/main/java/seedu/address/model/statistics/StackBarChartModel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/statistics/StackBarChart.java
  src/main/java/seedu/address/ui/statistics/StatsPieChart.java
  src/main/java/seedu/address/ui/statistics/StatsQns.java
  src/main/java/seedu/address/ui/statistics/StatsQnsListCard.java
  src/test/java/seedu/address/logic/commands/statistics/GetOverviewCommandTest.java
  src/test/java/seedu/address/logic/commands/statistics/GetQnsCommandTest.java
  src/test/java/seedu/address/logic/commands/statistics/GetReportCommandTest.java
  src/test/java/seedu/address/logic/commands/statistics/GetStatisticsCommandTest.java
  src/test/java/seedu/address/logic/parser/statistics/GetOverviewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/statistics/GetQnsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/statistics/GetReportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/statistics/GetStatisticsCommandParserTest.java
  src/test/java/seedu/address/testutil/QuizResultFilterBuilder.java
Labels: priority.Medium, severity.Low, type.Enhancement

#90 Make image support cross-platform
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/note/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/note/EditNoteCommand.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QuestionListCard.fxml
Labels: priority.High, severity.High, type.Bug

#91 Minor change in user guide
  docs/UserGuide.adoc
Labels: priority.Low, severity.Low, type.Documentation

#92 [SHUI YAO] Make notfication to v2.0
  docs/UserGuide.adoc
Labels: priority.Low, severity.Low, type.Enhancement

#93 Expand initial sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, severity.Low, type.Enhancement

#94 [Irene] Add sample quiz result
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Low, severity.Low, type.Enhancement

#95 [SHUI YAO]Update Individual Project Portfolio
  docs/AboutUs.adoc
  docs/team/PortfolioShuiYao.adoc
  docs/team/shuiyao-sg.adoc
Labels: priority.Medium, severity.Medium, type.Documentation

#96 Polish developer guide and portfolio
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/team/parcly-taxel.adoc
Labels: priority.Medium, severity.Medium, type.Documentation

#99 Flesh out manual testing in developer guide
  docs/DeveloperGuide.adoc
Labels: priority.Medium, severity.Low, type.Documentation

#98 [Wang Xueting] PPP draft version
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/shirleywangxt.adoc
  src/main/java/seedu/address/logic/commands/questioncommands/AddQuestionCommand.java
Labels: priority.Medium, severity.Medium, type.Documentation

#97 [Zhang Dongjun] Draft of portfolio
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/PortfolioDongjun.adoc
Labels: priority.Medium, severity.Medium, type.Documentation

#100 Rename some files
  docs/AboutUs.adoc
  docs/team/auxinnn.adoc
Labels: priority.Low, severity.Low, type.Documentation

#101 [Wang Xueting] Update user guide with screenshots
  docs/UserGuide.adoc
  docs/images/questionCommandsDemo/addqcommand.png
  docs/images/questionCommandsDemo/addqresult.png
  docs/images/questionCommandsDemo/clearcommand.png
  docs/images/questionCommandsDemo/clearresult.png
  docs/images/questionCommandsDemo/deleteqcommand.png
  docs/images/questionCommandsDemo/deleteqresult.png
  docs/images/questionCommandsDemo/difficultycommand.png
  docs/images/questionCommandsDemo/difficultyresult.png
  docs/images/questionCommandsDemo/editqcommand.png
  docs/images/questionCommandsDemo/editqresult.png
  docs/images/questionCommandsDemo/findqcommand.png
  docs/images/questionCommandsDemo/findqresult.png
  docs/images/questionCommandsDemo/listqcommand.png
  docs/images/questionCommandsDemo/listqresult.png
  docs/images/questionCommandsDemo/subjectcommand.png
  docs/images/questionCommandsDemo/subjectresult.png
Labels: priority.High, severity.Medium, type.Documentation
