Repository AY1920S1-CS2103T-F11-4/main, pull requests merged in 2019-11, with the labels that each got.

#103 [SHUI YAO] Update User Guide
  docs/UserGuide.adoc
  docs/images/UserGuideRes/TaskCommands/AddTaskForNote_command.png
  docs/images/UserGuideRes/TaskCommands/AddTaskForNote_success.png
  docs/images/UserGuideRes/TaskUI.png
  docs/team/shuiyao-sg.adoc
  gradle/wrapper/gradle-wrapper.properties
Labels: priority.High, type.Documentation

#127 [SHUI YAO] Fix time format error message
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/task/Task.java
Labels: priority.Medium, severity.Medium, type.Bug

#128 Fix some bugs raised in issues
  src/main/java/seedu/address/logic/parser/quiz/QuizModeCommandParser.java
  src/main/resources/view/QuizQuestionListCard.fxml
Labels: priority.High, severity.High, type.Enhancement

#143 Move image selection to after title checking
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ImageSelectionSequenceDiagram.puml
  docs/images/ImageSelectionSequenceDiagram.png
  docs/team/parcly-taxel.adoc
  src/main/java/seedu/address/logic/commands/note/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/note/EditNoteCommand.java
  src/main/java/seedu/address/logic/parser/note/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/note/EditNoteCommandParser.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedNoteTest.java
Labels: priority.High, severity.High, type.Bug

#145 Fix bugs and update for UG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/quiz/QuitQuizCommand.png
  docs/images/quiz/QuitQuizCommandResult.png
  docs/images/quiz/QuizAnswer.png
  docs/images/quiz/QuizAnswerResult.png
  docs/images/quiz/QuizModeCommand.png
  docs/images/quiz/QuizModeCommandResult.png
  docs/images/quiz/ShowAnswerCommand.png
  docs/images/quiz/SkipCommand.png
  docs/images/quiz/SkipCommandResult.png
  src/main/java/seedu/address/model/AppData.java
Labels: priority.Medium, severity.Medium, type.Documentation, type.Enhancement

#146 [Irene] Fix overview command date
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/irene-lly.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/statistics/GetOverviewCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetQnsCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetReportCommand.java
  src/main/java/seedu/address/logic/commands/statistics/GetStatisticsCommand.java
  src/main/java/seedu/address/logic/parser/statistics/GetOverviewCommandParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetQnsCommandParser.java
  src/main/java/seedu/address/logic/parser/statistics/GetStatisticsCommandParser.java
  src/main/java/seedu/address/model/quiz/QuizResult.java
  src/main/java/seedu/address/model/quiz/QuizResultFilter.java
  src/test/java/seedu/address/logic/commands/statistics/GetOverviewCommandTest.java
  src/test/java/seedu/address/logic/commands/statistics/GetQnsCommandTest.java
  src/test/java/seedu/address/logic/commands/statistics/GetReportCommandTest.java
  src/test/java/seedu/address/logic/commands/statistics/GetStatisticsCommandTest.java
  src/test/java/seedu/address/logic/parser/statistics/GetOverviewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/statistics/GetQnsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/statistics/GetStatisticsCommandParserTest.java
  src/test/java/seedu/address/testutil/QuizResultFilterBuilder.java
Labels: priority.High, severity.High, type.Bug

#144 Allow matching words in question body anywhere
  src/main/java/seedu/address/logic/commands/quiz/QuizModeCommand.java
  src/main/java/seedu/address/logic/parser/quiz/QuizModeCommandParser.java
  src/main/java/seedu/address/model/AppData.java
  src/main/java/seedu/address/model/question/BodyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/question/Question.java
Labels: priority.High, severity.High, type.Bug

#147 Update portfolio and UGDG of quiz feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/auxinnn.adoc
Labels: priority.Medium, severity.Medium, type.Documentation

#148 Implement dynamic image resizing
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/UsingPlantUml.adoc
  docs/team/parcly-taxel.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/note/EditNoteCommand.java
  src/main/java/seedu/address/logic/commands/questioncommands/EditQuestionCommand.java
  src/main/java/seedu/address/logic/commands/task/AddTaskForNoteCommand.java
  src/main/java/seedu/address/model/AppData.java
  src/main/java/seedu/address/model/question/UniqueQuestionList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/panels/NoteListCard.java
  src/main/java/seedu/address/ui/panels/NoteListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NoteListCard.fxml
  src/main/resources/view/NoteListPanel.fxml
  src/main/resources/view/QuestionListCard.fxml
  src/main/resources/view/QuestionListPanel.fxml
  src/main/resources/view/QuizQuestionListCard.fxml
  src/main/resources/view/StatsQnsListCard.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: priority.High, severity.High, type.Bug, type.Documentation

#149 Remove irrelevant quiz results
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, severity.Low, type.Task

#150 [Irene] Fix some issues
  docs/UserGuide.adoc
  docs/diagrams/StatisticsSequenceDiagram.puml
  docs/images/StatisticsSequenceDiagram.png
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/quiz/QuizResultList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/statistics/StackBarChart.java
  src/main/resources/view/DarkTheme.css
Labels: priority.Medium, severity.Medium, type.Bug

#151 Add heading for quiz panel
  src/main/resources/view/QuizQuestionListPanel.fxml
Labels: priority.Medium, severity.Medium, type.Enhancement

#153 [SHUI YAO] Support Edit Task Command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AppDataParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/task/EditTaskCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/data/JsonSerializableAppDataTest/duplicateTaskData.json
  src/test/data/JsonSerializableAppDataTest/typicalAppData.json
  src/test/java/seedu/address/testutil/TypicalAppData.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement

#154 Finalise UI, update DG and PPP
  docs/DeveloperGuide.adoc
  docs/images/Ui.png
  docs/team/parcly-taxel.adoc
Labels: priority.Low, severity.Low, type.Documentation, type.Enhancement

#155 [SHUI YAO]Implement FindTaskCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/task/FindTaskCommand.java
  src/main/java/seedu/address/logic/parser/AppDataParser.java
  src/main/java/seedu/address/logic/parser/task/FindTaskCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskContainsDatePredicate.java
  src/main/java/seedu/address/model/task/TaskContainsTimePredicate.java
  src/main/java/seedu/address/model/task/TaskHeadingContainsKeyWordPredicate.java
  src/main/java/seedu/address/model/task/TaskPredicate.java
Labels: priority.High, severity.High, type.Enhancement

#156 Update for portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/auxinnn.adoc
Labels: priority.Low, severity.Low, type.Documentation

#158 [SHUI YAO]Update UG & DG
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/TaskClassDiagram.puml
  docs/diagrams/task/AddTaskForNoteSequenceDiagram.puml
  docs/diagrams/task/TaskClassDiagram.puml
  docs/images/TaskClassDiagram.png
  docs/images/task/AddTaskForNoteSequenceDiagram.png
  docs/images/task/TaskClassDiagram.png
  src/main/resources/view/QuestionListCard.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: priority.Medium, type.Documentation

#159 [Wang Xueting] Modify findq command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/questioncommands/FindQuestionCommand.java
  src/main/java/seedu/address/logic/parser/questionparser/FindQuestionCommandParser.java
  src/main/java/seedu/address/model/question/BodyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/question/QuestionContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/questioncommands/FindQuestionCommandTest.java
  src/test/java/seedu/address/logic/parser/AppDataParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/question/QuestionContainsKeywordsPredicateTest.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#160 Polish other parts of the user guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.Low, severity.Low, type.Documentation

#161 Update of UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.Low, severity.Low, type.Documentation

#162 Add wrapText for quiz
  src/main/resources/view/QuizQuestionListCard.fxml
Labels: priority.Low, severity.Low, type.Enhancement

#163 [Irene ]Add wraptext for statistics labels in fxml file
  src/main/java/seedu/address/ui/statistics/StackBarChart.java
  src/main/java/seedu/address/ui/statistics/StatsPieChart.java
  src/main/resources/view/StackBarChart.fxml
  src/main/resources/view/StatsPieChart.fxml
  src/main/resources/view/StatsQnsListCard.fxml
Labels: priority.Low, severity.Low, type.Enhancement

#164 Remove PlantUML tutorial
  docs/UsingPlantUml.adoc
  docs/diagrams/plantuml/AbeforeC.puml
  docs/diagrams/plantuml/AllDown.puml
  docs/diagrams/plantuml/ArrowLength.puml
  docs/diagrams/plantuml/CbeforeA.puml
  docs/diagrams/plantuml/HiddenArrows.puml
  docs/diagrams/plantuml/PackagesAndConsistency.puml
  docs/diagrams/plantuml/UpAndDown.puml
  docs/images/plantuml/ABeforeC.png
  docs/images/plantuml/AllDown.png
  docs/images/plantuml/ArrowLength.png
  docs/images/plantuml/CBeforeA.png
  docs/images/plantuml/ConfiguringGraphviz.png
  docs/images/plantuml/EditingDeleteSequenceDiagram.png
  docs/images/plantuml/HiddenArrows.png
  docs/images/plantuml/PackagesAndConsistency.png
  docs/images/plantuml/RawUiDiagram.png
  docs/images/plantuml/UpAndDown.png
Labels: priority.Low, severity.Low, type.Documentation

#169 Update UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/quiz/QuitQuizCommand.png
  docs/images/quiz/QuitQuizCommandResult.png
  docs/images/quiz/QuizAnswer.png
  docs/images/quiz/QuizAnswerResult.png
  docs/images/quiz/QuizModeCommand.png
  docs/images/quiz/QuizModeCommandResult.png
  docs/images/quiz/ShowAnswerCommand.png
  docs/images/quiz/SkipCommand.png
  docs/images/quiz/SkipCommandResult.png
  docs/team/auxinnn.adoc
Labels: priority.Low, severity.Low, type.Documentation

#168 [SHUI YAO]Update UG
  docs/UserGuide.adoc
  docs/diagrams/AddTaskForNoteSequenceDiagram.puml
  docs/diagrams/TaskClassDiagram.puml
  docs/diagrams/task/AddTaskForNoteSequenceDiagram.puml
  docs/images/UserGuideRes/TaskCommands/AddTaskForNote_command.png
  docs/images/UserGuideRes/TaskCommands/AddTaskForNote_success.png
  docs/images/UserGuideRes/TaskCommands/DeleteTaskCommand.png
  docs/images/UserGuideRes/TaskCommands/DeleteTaskCommand_success.png
  docs/images/UserGuideRes/TaskCommands/DoneTaskCommand.png
  docs/images/UserGuideRes/TaskCommands/DoneTaskCommand_success.png
  docs/images/UserGuideRes/TaskUI.png
Labels: priority.Low, severity.Low, type.Documentation

#170 [irene] resolve issue with overview dates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/StatisticsClassDiagram.puml
  docs/images/StatisticsClassDiagram.png
  docs/images/statistics/StatisticsActivityDiagram.png
  docs/images/statistics/StatisticsClassDiagram.png
  docs/images/statistics/overview.PNG
  docs/images/statistics/question.PNG
  docs/images/statistics/report.PNG
  docs/images/statistics/stats.PNG
  src/main/java/seedu/address/logic/parser/statistics/GetOverviewCommandParser.java
Labels: priority.High, severity.High, type.Bug, type.Documentation

#171 [SHUI YAO]Update UG
  docs/UserGuide.adoc
  docs/images/UserGuideRes/TaskCommands/AddTaskForNote_command.png
  docs/images/UserGuideRes/TaskCommands/AddTaskForNote_success.png
  docs/images/UserGuideRes/TaskCommands/DeleteTaskCommand.png
  docs/images/UserGuideRes/TaskCommands/DeleteTaskCommand_success.png
  docs/images/UserGuideRes/TaskCommands/DoneTaskCommand.png
  docs/images/UserGuideRes/TaskCommands/DoneTaskCommand_success.png
  docs/images/UserGuideRes/TaskUI.png
Labels: type.Documentation

#172 [Zhang Dongjun] Update for UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/QuizModeSequenceDiagram.puml
  docs/images/QuizModeSequenceDiagram.png
  docs/images/quiz/QuitQuizCommand.png
  docs/images/quiz/QuitQuizCommandResult.png
  docs/images/quiz/QuizAnswer.png
  docs/images/quiz/QuizAnswerResult.png
  docs/images/quiz/QuizModeCommand.png
  docs/images/quiz/QuizModeCommandResult.png
  docs/images/quiz/ShowAnswerCommand.png
  docs/images/quiz/SkipCommand.png
  docs/images/quiz/SkipCommandResult.png
  docs/team/auxinnn.adoc
Labels: priority.Low, severity.Low, type.Documentation

#174 [SHUI YAO]Update UG&DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddTaskForNoteCommandExecuteSequenceDiagram.puml
  docs/diagrams/AddTaskForNoteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/task/AddTaskForNoteCommandExecuteSequenceDiagram.png
Labels: type.Documentation

#175 Fix language in DG
  docs/DeveloperGuide.adoc
Labels: priority.Low, severity.Low, type.Documentation

#176 [Irene] Update User and Developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/StatisticsSequenceDiagram.puml
  docs/images/StatisticsSequenceDiagram.png
  docs/team/irene-lly.adoc
  src/main/java/seedu/address/model/quiz/QuizResultList.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Low, severity.Low, type.Documentation, type.Enhancement

#177 [Irene] Add intro to developer guide and resize some images
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/statistics/StatisticsActivityDiagram.png
  docs/images/statistics/StatisticsClassDiagram.png
  docs/images/statistics/StatisticsSequenceDiagram.png
Labels: priority.Low, severity.Low, type.Documentation

#178 Table of contents and language for developer guide
  docs/DeveloperGuide.adoc
  docs/team/parcly-taxel.adoc
Labels: priority.Low, severity.Low, type.Documentation

#179 [Irene] Standardise verbs in StatisticsActivityDiagram
  docs/diagrams/StatisticsActivityDiagram.puml
  docs/images/statistics/StatisticsActivityDiagram.png
Labels: priority.Low, severity.Low, type.Documentation

#180 [SHUI YAO] Update PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddTaskForNoteActivityDiagram.puml
  docs/diagrams/AddTaskForNoteCommandExecuteSequenceDiagram.puml
  docs/diagrams/HasValidNoteSequenceDiagram.puml
  docs/images/task/AddTaskForNoteActivityDiagram.png
  docs/images/task/AddTaskForNoteCommandExecuteSequenceDiagram.png
  docs/images/task/HasValidNoteSequenceDiagram.png
  docs/team/auxinnn.adoc
  docs/team/irene-lly.adoc
  docs/team/parcly-taxel.adoc
  docs/team/shirleywangxt.adoc
  docs/team/shuiyao-sg.adoc
Labels: priority.Low, severity.Low, type.Documentation

#181 [SHUI YAO] Minor fix on PPP
  docs/team/shuiyao-sg.adoc
Labels: priority.Low, severity.Low, type.Documentation

#182 [SHUI YAO] Fix indentation of use case
  docs/DeveloperGuide.adoc
Labels: type.Documentation

#183 [Zhang Dongjun] Language improvement for ppp
  docs/team/auxinnn.adoc
Labels: priority.Low, severity.Low, type.Documentation

#185 [Zhang Dongjun] Fix language and add QuizResultClassDiagarm
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/QuizResultClassDiagram.puml
  docs/images/QuizResultClassDiagram.png
  docs/team/auxinnn.adoc
Labels: priority.Low, severity.Low, type.Documentation

#186 [Wang Xueting] Modification to documentation version 4
  docs/DeveloperGuide.adoc
  docs/diagrams/QuestionClassDiagram.puml
  docs/team/shirleywangxt.adoc
Labels: priority.Low, severity.Low, type.Documentation

#187 Fix format of DG
  docs/DeveloperGuide.adoc
Labels: priority.Low, severity.Low, type.Documentation

#188 [SHUI YAO]Add manual testing instruction for task in DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.Medium, type.Documentation

#189 [SHUI YAO]JAVA code touched: reshuffle position of methods
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/AppData.java
  src/main/java/seedu/address/model/Model.java
Labels: priority.High, severity.High

#190 [Irene] Modify UG, DG and PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/StatisticsSequenceDiagram.puml
  docs/images/statistics/StatisticsSequenceDiagram.png
  docs/team/irene-lly.adoc
Labels: priority.Low, severity.Low, type.Documentation

#191 [SHUI YAO]Add remark for special notation (monospaced text) in DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.Low, severity.Low, type.Documentation
